name: Cleanup Old Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:      # <-- ADD THIS BLOCK
      actions: write  # <-- Grants permission to delete workflow runs
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 5
